import type { BucketListItem } from '../types/bucket';

export const SAMPLE_BUCKET_ITEMS: BucketListItem[] = [
  {
    id: 'sample-1',
    title: 'Witness the Northern Lights in Tromsø',
    description: 'Camp under polar skies, charter a dog-sledding expedition through Lyngen Alps, and document the Aurora Borealis through long-exposure analog medium format.',
    category: 'Travel',
    priority: 'HIGH',
    targetDate: '2025-11-15',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQcawQRvrWkrRO6I38dNmSAeNwiPBcMY5-x9m9gf6P_FCx85E_7GY4v5TnxERFrHGH9EG3dqXjjaXo-X-_iKchPMjWOVwpTRwQKMkJewhTusZrTMZkf4UNPklS69dOH8IUP21Pxi21zvo9TJ54nnldFRzasr3xgsUDPjbphAk2HOMki-H6pcP1OdjigW049nxz4YfKlNLicBX0_l_vMxjGlm4vRrGFTPQtLhwDdfDs39D18iHLDOGC',
    completed: false,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'sample-2',
    title: 'Summit Mount Kilimanjaro via Machame Route',
    description: '7-day acclimatization trek navigating five distinct ecological zones to stand at Uhuru Peak (5,895m) at dawn. Complete altitude training regimen.',
    category: 'Adventure',
    priority: 'HIGH',
    targetDate: '2025-09-20',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5CWTmjtnQv7G-28qwVIpvGWlS86UnnLhEffnln4rWMgvOapDLKVy2PsI2EyxC6hwREe-NA9sEsF3A0XqkcpuGpkeh17SOkvsQEtkJE0oEcPXv23x6UBsTOZChk6gPKUhoKinajiKYe4stlBilvyYptdP9y2sMt4Wmd2yX1bCnE0zoYiDawrM5VL8S1K_BNtp8u4TqwuWWOJeHtp7z3p27Mij4sL_qW2J8zepIBKtofZMiMwJKhYE7',
    completed: false,
    createdAt: '2024-02-14T11:30:00Z',
  },
  {
    id: 'sample-3',
    title: 'Publish Debut Nature Photography Monograph',
    description: 'Curate a limited 140-page hardcover publication chronicling 5 years of remote wilderness exploration, printed on FSC-certified unbleached Japanese cotton stock.',
    category: 'Creative & Art',
    priority: 'MEDIUM',
    targetDate: '2026-05-12',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBpkDZ3pkW3Lmo484oz0VDBmrh2ma7pEgMNy2UjTqYy2A8B69F8J40tAvviZRodVbc3McbgQ7N28UScilw0ZP0i8zeIujdYIiHXjH2Q0wjTbSR2ztOznnktjNR2AP4aWviq8HCBFXXEdPMqUXoHeTz_iBAgc8h1EVJoFjZaCKzDtQBspj9zdh55BfXXQuWb9IzuR_Msgw8fvGiaeUTegaXqhkonQzGfK1n9Z4acy8_8yYQHKAJ2V1Jj',
    completed: false,
    createdAt: '2024-03-01T09:15:00Z',
  },
  {
    id: 'sample-4',
    title: 'Run the Athens Authentic Marathon',
    description: 'Conquered the historic 42.195km route from Marathon battlefield to the Panathenaic Stadium. Vault archival certificate registered in vault ledger.',
    category: 'Health & Fitness',
    priority: 'HIGH',
    targetDate: '2024-11-09',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCM0JqMZfNVmlomaM01FmFipBrIfv93GPCGXhmV42Pi--BeDfvEelsfLbrM-7YVqvXo_3uIBqudcRwi9zPyY6aO0nblqBaBPT1DlHfHwoHuCJyE75Mps7PR3qpVm_onJRiHnLlezfb32xhkk8fvLKgapsr10IVqp5um2HntreW-zpGOPWpwcLIdnznfHHBnwGgDvT-gE57YJsSQHLeY1lehVRsZGlZhJfrcPlA-RzsbzkX7o6a2EMvP',
    completed: true,
    createdAt: '2023-11-10T14:20:00Z',
  },
  {
    id: 'sample-5',
    title: 'Acquire Conversational Fluency in Japanese (JLPT N3)',
    description: 'Master 650 Kanji characters and 3,700 vocabulary terms for immersion travel. Daily flashcards, weekly native conversation exchanges, and reading classic haiku.',
    category: 'Learning & Career',
    priority: 'LOW',
    targetDate: '2025-12-31',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuASi82CQZEADihUXqee26PP4IBKAPENsAZWfoTjYjB4pdkm8DnUsXqTRYWAM6rfjMgoSIMfLEF6FuW4V4eOHkF_na148T00S9cUeSlx30TjOdiK9joQLq1PhmnhH-PjgrqSPGazul3PZeZyfVDkfbKYqUvw00aBbEj9igBWAawOn4_v8qYqShxmH5g550ob5V-gT8rTaKh7E_YvsEFP__IC_rPCFJPaVRHFDGGLmNAGvBz0DXChWrtg',
    completed: false,
    createdAt: '2024-04-05T08:00:00Z',
  },
  {
    id: 'sample-6',
    title: 'Build an Off-Grid Sustainable Solar Cabin in Vermont',
    description: 'Acquire 12 acres of mixed hardwood terrain, secure permits for micro-hydro and 8kW solar array, and construct a passive-house certified writer\'s studio sanctuary.',
    category: 'Finance & Wealth',
    priority: 'HIGH',
    targetDate: '2026-08-14',
    imageKey: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGkSk5UfknxsfNL3iJW9CQItVkkaG9mM-t-7ALfbfd3CzSt0887aYjFlIMMM4jru5Ww-GenlA9GGVar6hvclTJW0tWcGjhsroe0qzU8rwMRcJMJ68TFz_S3HNI0JN8XMFwcJE2S_wWhxqqxRHqs2f-f2hTzRIxDhfUyQRHxLLHxC7GWQGlELyO6cy8kmUBYprQBUdQ3TMcY66Oh2SwGJJ_u16E27o7_NkhYYRbhQEcxt8OYdw3jU6q',
    completed: false,
    createdAt: '2024-05-18T16:45:00Z',
  },
];

export const AVATAR_ARCHETYPES = [
  {
    id: 'elena',
    name: 'Elena Vance (Active)',
    role: 'Master Voyager',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuRFpEHAdtVSPlvvfDTmOQFG6uIg7bxVFr90WYN-XU6-sep49l7iTqnGuhLYVg56evbuBptsgAjw4IzI8-DIoj4DYI-Ow-zBptWg1fjGX-mcdY7XQvzypVauAxEmN2f2C9q9dV1R2Fk1RvIZfJ7mvWrIRhJZRAKBO2L6LfrYqeE3t_HRXhCsI4WDUFM1IYaiD-VMK0PdTDtTdEa2kSfpSjeM1ChA6lG5VWYb9yABf0NYOyzCvPpke5',
  },
  {
    id: 'alpine',
    name: 'High Alpine Explorer',
    role: 'Alpine',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmpqPRFluoGY4Rx7O4eULZak0JYISA-f0sgZsbnXINoy7WE5D4h3kqL0bjmxDEIdesJ4QWjDQH_5lJFKgiCLCG2e3j4VlYl42ti-KsiqTbbGyaEtUqPhzEzynr282ZjZeAp2OfMJS_GTCfwi8XC6yn832-WxQNUxTbyuDibw09re2mNguj-OS7DrCOjNDgUOeLeePQueI4DWIfZHL6nsX1RGsd4ehqyKdgBAKnCazhiB1ZjAAcCVYj',
  },
  {
    id: 'navigator',
    name: 'Maritime Navigator',
    role: 'Navigator',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFAXw93gzrUOtOpHPWPDrbmSycin6H_6vUYQ73tsdwK2-6VJyjQ2rk8d_8zM2u8yjEh4VQ3r5mNwom9dpMDZ4hkpHHXqZegFIKUaeNy0Day2B8jpPbyKdBpSK3Ir12ClP_k_6tsK4yw3_uFTSs8tCkhROqGkQ5k68f3c21YEYNXYFSZhqT8S4KL8-avW6UXG1jEizqShSLVIBsMjnEzrL8hmAAlbAXUIkkwwT4XoIRPLNhMGAQ1Xhr',
  },
  {
    id: 'botanist',
    name: 'Field Botanist',
    role: 'Botanist',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgq0qNVrGtvqSgCTCpXZucMO1yvWxjuKgVQ4wVNnE_YI_COgpOwEIkV2oBr_Q2ywPseQeoEao2AWMoW7gUOq9IiHUwpsi3Hsz_jaX8VueoEMRGNfwJbmscPlZO_979t1g4zLlFq3jpalNoYDGYxE5V8KPv-q5pTSb4w0fmuE4GJvlgyVmiu5oZtxu7tiyfet6hlFOb15I9BwSqsHz4dhVxXD2q16yZGwb5lsO2L-n8ld9tT6Ao-0Rv',
  },
  {
    id: 'wayfarer',
    name: 'Solitary Wayfarer',
    role: 'Wayfarer',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMruiILMYMfoLt44fRWF_NuwGoHOfjw8C9ZtBf8Tpw_vW6ZGKJPXtts0G2pVQD69gXETR11QFll0FprE6c75nyTXQCD2ilmvxkZJ0QH35DfxTQyoIodd9OJxQTf5fnLL7LdB9CQvgtNHdonQYg4kaVwByMkyK8sl0kvSB8tHfOW0qNCiwGaj_C0wvK1lWZDY_wH2PLRWkXH6NRQ99Tf30wcBq-bEfB2c4ZbstMQlx5tLBr6OQ7c4ep',
  },
];
